### ISSUE TITLE
Memory Error while installing requirements

### ISSUE THREAD

**Issue by aboda28** [SevaSk/ecoute#106]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd ecoute

C:\Windows\System32\ecoute>python -c "with open('keys.py', 'w', encoding='utf-8'
) as f: f.write('OPENAI_API_KEY=\"API KEY\"')"

C:\Windows\System32\ecoute>python -c "with open('keys.py', 'w', encoding='utf-8'
) as f: f.write('OPENAI_API_KEY=\"sk-wNfFJHUHCH0br8F180Y8T3BlbkFJFQs4QnTzBS5fi15
1hKqW\"')"

C:\Windows\System32\ecoute>python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\Windows\System32\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

C:\Windows\System32\ecoute>python3 main.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\ecoute>python main.py --api
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\Windows\System32\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

C:\Windows\System32\ecoute>python3 main.py --api
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\ecoute>python3 main.py --api
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32\ecoute>python main.py --api
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\Windows\System32\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

C:\Windows\System32\ecoute>cd..

C:\Windows\System32>cd
C:\Windows\System32

C:\Windows\System32>
C:\Windows\System32>
C:\Windows\System32>cd..

C:\Windows>cd..

C:\>d:

D:\>cd ecoute

D:\ecoute>pip install --upgrade pip
Requirement already satisfied: pip in c:\users\windows\appdata\local\programs\py
thon\python38\lib\site-packages (21.1.1)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 328 kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
ERROR: Could not install packages due to an OSError: [WinError 5] Access is deni
ed: 'C:\\Users\\windows\\AppData\\Local\\Programs\\Python\\Python38\\~cripts\\pi
p.exe'
Consider using the `--user` option or check the permissions.

D:\ecoute>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu
117
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status
=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='
download.pytorch.org', port=443): Read timed out. (read timeout=15)")': /whl/cu1
17/numpy/
Collecting numpy==1.24.3 (from -r requirements.txt (line 1))
  Using cached numpy-1.24.3-cp38-cp38-win_amd64.whl (14.9 MB)
Collecting openai-whisper==20230314 (from -r requirements.txt (line 2))
  Using cached openai-whisper-20230314.tar.gz (792 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Wave==0.0.2 (from -r requirements.txt (line 3))
  Using cached Wave-0.0.2.zip (38 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting openai==0.27.6 (from -r requirements.txt (line 4))
  Using cached openai-0.27.6-py3-none-any.whl (71 kB)
Collecting customtkinter==5.1.3 (from -r requirements.txt (line 5))
  Using cached customtkinter-5.1.3-py3-none-any.whl (295 kB)
Collecting PyAudioWPatch==0.2.12.5 (from -r requirements.txt (line 6))
  Using cached PyAudioWPatch-0.2.12.5-cp38-cp38-win_amd64.whl (85 kB)
Collecting torch (from -r requirements.txt (line 8))
  Downloading https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp38-cp
38-win_amd64.whl (2343.7 MB)
     ---------------------------------------  2.3/2.3 GB 1.5 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool_
_
    return any(self)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexp
r>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_bu
ilt
    candidate = func()
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_
from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_dist
ribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)

  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\operations\prepare.py", line 587, in _prepare_linked_requirement

    local_file = unpack_url(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\cachecontrol\filewrapper.py", line 96, in read
    self._close()
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\cachecontrol\filewrapper.py", line 76, in _close
    self.__callback(result)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\cachecontrol\controller.py", line 353, in cache_response
    self._cache_set(cache_url, request, response, body, expires_time)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\cachecontrol\controller.py", line 274, in _cache_set
    self.serializer.dumps(request, response, body),
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\cachecontrol\serialize.py", line 70, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\fallback.py", line 883, in pack
    self._pack(obj)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\fallback.py", line 862, in _pack
    return self._pack_map_pairs(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\fallback.py", line 968, in _pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\fallback.py", line 862, in _pack
    return self._pack_map_pairs(
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\fallback.py", line 967, in _pack_map_pairs
    self._pack(k, nest_limit - 1)
  File "c:\users\windows\appdata\local\programs\python\python38\lib\site-package
s\pip\_vendor\msgpack\fallback.py", line 815, in _pack
    return self._buffer.write(obj)
MemoryError

D:\ecoute>

**Comment by rmhckrkz** [comment]
@aboda28 please, uninstall python and reinstall again other version. Looks like you have more than one version of python and the issue is with path.
