### ISSUE TITLE
problem with main.py

### ISSUE THREAD

**Issue by saiggs** [SevaSk/ecoute#109]
PS C:\Windows\system32\ecoute> python main.py
C:\Users\pppp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
Traceback (most recent call last):
  File "C:\Windows\system32\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\Windows\system32\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ImportError: cannot import name 'OPENAI_API_KEY' from 'keys' (C:\Windows\system32\ecoute\keys.py)

**Comment by markomeyyer** [comment]
me too

**Comment by rmhckrkz** [comment]
@markomeyyer @saiggs hi guys. Create keys.py file manually.
