### ISSUE TITLE
Anyone got this error ? 

### ISSUE THREAD

**Issue by markomeyyer** [SevaSk/ecoute#111]
PS C:\WINDOWS\system32\ecoute> python main.py
C:\Users\Setup Game\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Traceback (most recent call last):
  File "C:\WINDOWS\system32\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\WINDOWS\system32\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
  File "C:\WINDOWS\system32\ecoute\keys.py", line 1, in <module>
    OPENAI_API_KEY=sk-YUZEWEkiYtzMxAJmcRNiT3BlbkFJyQv8ZRVOAnbDdsNj

**Comment by markomeyyer** [comment]
I changed the API number just need an example on how to sort this please

**Comment by rmhckrkz** [comment]
@markomeyyer please, put your API key between "" in keys.py file

**Comment by NEUCFgod** [comment]
Hello，when I run python main.py，there is a error ：“Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/audio/transcriptions (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))))”. Can you help me?

**Comment by NEUCFgod** [comment]
我已经将 API 密钥放在 keys.py 文件中的“”之间

**Comment by NEUCFgod** [comment]
I have put my API key between "" in keys.py file， still error “Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/audio/transcriptions (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))))”

**Comment by jiangyin14** [comment]
> I have put my API key between "" in keys.py file， still error “Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/audio/transcriptions (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)'))))”

换梯子吧，你这个梯子没ssl或者ssl有bug
