### ISSUE TITLE
ModuleNotFoundError: No module named 'whisper'

### ISSUE THREAD

**Issue by yuanxiaochenAC** [SevaSk/ecoute#112]
All things go well, until I run "python main.py".the outcome shows like:
Traceback (most recent call last):
  File "C:\Users\AAA\ecoute\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\Users\AAA\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'

I don't know how to deal with it, can you help me？

**Comment by adityagoel28** [comment]
pip install whisper

**Comment by fad743** [comment]
i have a same error, please write proper command

**Comment by fad743** [comment]
> pip install whisper

hey boss.. did you solve this issue?

**Comment by adityagoel28** [comment]
> > pip install whisper
> 
> hey boss.. did you solve this issue?

Yes

**Comment by fad743** [comment]
can you also help me in this regard? please send me the command so i try one.
