### ISSUE TITLE
error to run pyhton main.py

### ISSUE THREAD

**Issue by Bhaloosky** [SevaSk/ecoute#132]
Hello, can you help me with how to fix this on my PC? Thank you.

PS C:\Users\user\ecoute> python main.py
C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
Traceback (most recent call last):
  File "C:\Users\user\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\Users\user\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ModuleNotFoundError: No module named 'keys'

**Comment by Adarsha-gg** [comment]
create a file named keys.py in the same directory with your open AI key. It would fix the issue.
