### ISSUE TITLE
No Transcription, and no response from Open AI

### ISSUE THREAD

**Issue by TayoGitCat** [SevaSk/ecoute#134]
Hello I am getting no response from external head phone and no response from Open AI API for transcription. Bellow is my error:
C:\Users\Tayo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
Operating as a standalone client
Using Open AI API for transcription.
READY
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\tayo\transcribe\ui.py", line 84, in update_response_ui
    responder.set_response_interval(update_interval)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GPTResponder' object has no attribute 'set_response_interval'

**Comment by TayoGitCat** [comment]
I get the following error consistently:
C:\tayo\transcribe>python main.py --api
C:\Users\Tayo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
***********************
************************
************************
File "C:\tayo\transcribe\ui.py", line 84, in update_response_ui
responder.set_response_interval(update_interval)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GPTResponder' object has no attribute 'set_response_interval'

**Comment by TayoGitCat** [comment]
According to research, "This error can occur if you are using an older version of the azure-ai-language-conversations package."
I have ran the following command.
pip install --upgrade azure-ai-language-conversations
