### ISSUE TITLE
Issue in running main.py

### ISSUE THREAD

**Issue by sahiillx** [SevaSk/ecoute#140]
PS D:\ProjectPro\ecoute-main> python main.py                                
Traceback (most recent call last):
  File "D:\ProjectPro\ecoute-main\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "D:\ProjectPro\ecoute-main\AudioTranscriber.py", line 1, in <module>
    import whisper
  File "C:\Python311\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

I am getting this error.

**Comment by vivekuppal** [comment]
This is the exact same error as https://github.com/vivekuppal/transcribe/issues/35

**Comment by sahiillx** [comment]
Hey @vivekuppal Thankyou So much
