### ISSUE TITLE
keys import issue

### ISSUE THREAD

**Issue by nandu2106** [SevaSk/ecoute#145]
S C:\ecoute\ecoute> python main.py --api
C:\Users\nandu\anaconda3\Lib\site-packages\whisper\timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
Traceback (most recent call last):
  File "C:\ecoute\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\ecoute\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY

I am getting this error.  i created an openapi key and created a keys.py as mentioned in the steps

**Comment by Dhonimadugu** [comment]
I'm also getting same error. Please suggest
