### ISSUE TITLE
ModuleNotFoundError: No module named 'whisper'. MAC OS

### ISSUE THREAD

**Issue by Cabdil1** [SevaSk/ecoute#177]
when i completed all requirements to use ecoute last minute it displayed this error
i tried to search solution of this issue but i didn’t got in issues section anyone that asked this question didn’t got full answer please help us.

abdulk@Abdus-MacBook-Pro ecoute % python main.py
Traceback (most recent call last):
  File "/Users/abdulk/ecoute/main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "/Users/abdulk/ecoute/AudioTranscriber.py", line 1, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
abdulk@Abdus-MacBook-Pro ecoute % 

please anyone can help me thanks

**Comment by Cabdil1** [comment]
pip3 install -r requirements.txt
