### ISSUE TITLE
Torch library issue

### ISSUE THREAD

**Issue by Abhisheknakka** [SevaSk/ecoute#180]
issue with torch library issue.

import torch
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import torch
  File "C:\Users\nsnai\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\nsnai\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by ossamamahjour** [comment]
@Abhisheknakka did get any news answers regarding this issue

**Comment by waldyd** [comment]
Modifying requirements.txt worked for me:

```
numpy==1.24.3
openai-whisper==20230314
Wave==0.0.2
openai==0.27.6
customtkinter==5.1.3
PyAudioWPatch==0.2.12.5
--extra-index-url https://download.pytorch.org/whl/cu117
torch==2.3.1
```

[1] https://stackoverflow.com/questions/78114412/import-torch-how-to-fix-oserror-winerror-126-error-loading-fbgemm-dll-or-depen
