### ISSUE TITLE
Issue with the GPTResponsder + quota of chatgpt 

### ISSUE THREAD

**Issue by zeeshankhanzk81** [SevaSk/ecoute#183]
When I run main.py via powershell [as administrator] then i get following error:
PS C:\WINDOWS\system32\ecoute> python main.py
Traceback (most recent call last):
  File "C:\WINDOWS\system32\ecoute\main.py", line 3, in <module>
    from GPTResponder import GPTResponder
  File "C:\WINDOWS\system32\ecoute\GPTResponder.py", line 2, in <module>
    from keys import OPENAI_API_KEY
ModuleNotFoundError: No module named 'keys'

When I run main.py directly by double clicking on it [from the location it is stored using windows explorer], after checking mic and speaker then ecoute app opens, when i speak then i get the following error message, i haven't exceeded my limit and using free version of chatgpt3.5. how this issue can be resolved? thanks

[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
[INFO] Whisper using GPU: False
READY
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

**Comment by andyoso** [comment]
Same problem, I have no idea how to deal with it.

**Comment by adirasgithub** [comment]
Problem is 
1. Now Torch, Cuda, Python are not compatible with each other, you would need to reinstall everything with compatibility check
2. whl wheel also has unsupported versions
The CUDA version compatibility depends on the specific version of PyTorch you're installing.
`--extra-index-url https://download.pytorch.org/whl/cu117`

This line suggests that you're trying to install a PyTorch version compatible with CUDA 11.7. However, as of now, PyTorch officially supports up to CUDA 11.3.
If you're using CUDA 11.7, you might need to downgrade your CUDA version to 11.3 or wait until PyTorch releases a version compatible with CUDA 11.7.

Once you do it, do 
`pip uninstall torch torchvision torchaudio`
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117` // 117 or 113, still unsure 

**Check python version**
`python --version`

**Check the CUDA version:**
`nvcc --version `(If CUDA Toolkit is installed)
OR 
`nvidia-smi` (To check driver's CUDA capability):

**Check Torch and Cuda compatibility** 
`python`
`import torch`
`print(torch.version.cuda)`
OR
you can also use 
`import torch`
`print(torch.__version__)`
`print(torch.cuda.is_available())  # Optional: Check for CUDA support`
Error Output: If you get an ImportError: No module named 'torch', then PyTorch is not installed.
Output : True , everything is working fine
Output : False , Retry, you are in trouble

**Comment by andyoso** [comment]
It still can't work : (
![image](https://github.com/SevaSk/ecoute/assets/39046697/b62db2da-cde4-404d-a074-aee68f94ff20)
