### ISSUE TITLE
Facing an issue while running main.py

### ISSUE THREAD

**Issue by tyusrogue** [SevaSk/ecoute#46]
PS C:\WINDOWS\system32\ecoute> python main.py
Traceback (most recent call last):
  File "C:\WINDOWS\system32\ecoute\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\WINDOWS\system32\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
  File "C:\Users\Lazyv\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lazyv\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by shenhuanum1** [comment]
The error occurs because `libc = ctypes.CDLL(libc_name)` is trying to load a dynamic link library named `libc_name`, but the value of `libc_name` is `None`. In Python, a value of type `None` cannot be iterated, which means it cannot be used in '/' or '\' operations. This leads to the error `TypeError: argument of type 'NoneType' is not iterable`.

This could be because `libc_name` has not been properly initialized or assigned, or a function that should have returned the name of the library in the previous code returned `None`. You need to check your code to ensure that `libc_name` has been properly assigned before it is passed to `ctypes.CDLL()`. You can add print statements or use a debugger to see the value of `libc_name` to determine whether it has been correctly assigned by the time this line of code is executed.
