### ISSUE TITLE
Returning an error while running the main.py

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [SevaSk/ecoute#61]
I have successfully installed all the libraries. Then i tried running the python main.py and python main.py -- Both are returning same error which is below

```
(base) PS C:\Users\nithi\Downloads\ecoute> python main.py --api
Traceback (most recent call last):
  File "C:\Users\nithi\Downloads\ecoute\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "C:\Users\nithi\Downloads\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
  File "C:\Users\nithi\anaconda3\lib\site-packages\whisper\__init__.py", line 13, in <module>
    from .model import ModelDimensions, Whisper
  File "C:\Users\nithi\anaconda3\lib\site-packages\whisper\model.py", line 13, in <module>
    from .transcribe import transcribe as transcribe_function
  File "C:\Users\nithi\anaconda3\lib\site-packages\whisper\transcribe.py", line 20, in <module>
    from .timing import add_word_timestamps
  File "C:\Users\nithi\anaconda3\lib\site-packages\whisper\timing.py", line 7, in <module>
    import numba
  File "C:\Users\nithi\anaconda3\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\nithi\anaconda3\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\nithi\anaconda3\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
```
![image](https://github.com/SevaSk/ecoute/assets/129744879/b5fa16c1-7fa6-45d0-a22f-b5e1171e0a85)

I'm not sure what's the problem is. Can anyone please look into this error?

**Comment by nithinreddyyyyyy** [comment]
> Do you have the correct versions?

I tried installing it, it is returning "Cannot install llvmlite". So, I have installed some another version of it.

![image](https://github.com/SevaSk/ecoute/assets/129744879/44f94389-7ec7-402e-821c-609c79fa67e2)

**Comment by SevaSk** [comment]
Not sure, you could try getting a simple whisper https://github.com/openai/whisper script up and running to try to see what is wrong

**Comment by nithinreddyyyyyy** [comment]
> Not sure, you could try getting a simple whisper https://github.com/openai/whisper script up and running to try to see what is wrong

It is working. Below is the screenshot

![image](https://github.com/SevaSk/ecoute/assets/129744879/cc2d4ec9-2af4-47b7-ad5c-f982246da78d)

**Comment by SevaSk** [comment]
Honestly no clue. I see a similar issue here https://github.com/numba/numba/issues/8615 but IDK how to resolve this.
