### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by Zulks01** [SevaSk/ecoute#80]
When I run the pip Install -r requirements.txt as per below I get a MemoryError

any ideas what is happening here? I have checked the installation of Python which is ok

C:\ecoute-main>pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting numpy==1.24.3
  Downloading numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
     ---------------------------------------- 14.8/14.8 MB 4.5 MB/s eta 0:00:00
Collecting openai-whisper==20230314
  Downloading openai-whisper-20230314.tar.gz (792 kB)
     ---------------------------------------- 792.9/792.9 kB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Wave==0.0.2
  Downloading Wave-0.0.2.zip (38 kB)
  Preparing metadata (setup.py) ... done
Collecting openai==0.27.6
  Downloading openai-0.27.6-py3-none-any.whl (71 kB)
     ---------------------------------------- 71.9/71.9 kB 3.9 MB/s eta 0:00:00
Collecting customtkinter==5.1.3
  Downloading customtkinter-5.1.3-py3-none-any.whl (295 kB)
     ---------------------------------------- 295.2/295.2 kB 4.6 MB/s eta 0:00:00
Collecting PyAudioWPatch==0.2.12.5
  Downloading PyAudioWPatch-0.2.12.5-cp311-cp311-win_amd64.whl (85 kB)
     ---------------------------------------- 85.9/85.9 kB 5.0 MB/s eta 0:00:00
Collecting torch
  Downloading https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp311-cp311-win_amd64.whl (2343.6 MB)
     ---------------------------------------  2.3/2.3 GB 3.8 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_internal\commands\install.py", line 400, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Program Files\Python311\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr

**Comment by Zulks01** [comment]
Space issue on local directory, creating some space resolved this issue.

**Comment by rmhckrkz** [comment]
Hi @Zulks01 @SevaSk @zarifpour @emcf @SpencerRightsma! Can you help with resolution of that issue?
