### ISSUE TITLE
unable to run main.py successfully

### ISSUE THREAD

**Issue by saravanareddy09** [SevaSk/ecoute#95]
**here is the issue im facing**
![issue on ecoute](https://github.com/SevaSk/ecoute/assets/135105015/7a13a668-55b1-4761-b58a-06a9a2657bf1)

Traceback (most recent call last):
  File "F:\AI\ecoute\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "F:\AI\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by s0d3s** [comment]
[Similar issue](https://github.com/SevaSk/ecoute/issues/99). Try to test the [solution](https://github.com/SevaSk/ecoute/issues/99#issuecomment-1586735424).
