### ISSUE TITLE
Error when executing main file 

### ISSUE THREAD

**Issue by MinhHoan147** [SevaSk/ecoute#99]
I've followed the steps according to the README. Everything was fine until I ran the command "py main.py --api". Can anyone help me to fix this problem?. Thanks a lot. 
I'm using: Choco version "1.2.1" and Python version: "3.9.12"

![Screenshot (102)](https://github.com/SevaSk/ecoute/assets/72193415/49bc1a37-4fe8-41a1-b598-5190dae2d76f)

**Comment by s0d3s** [comment]
Somehow you installed another library with the same name (`whisper`, but for work you need `openai-whisper`)

Try reinstalling via:

```bash
pip uninstall whisper
pip install git+https://github.com/openai/whisper.git 
```

[Source](https://github.com/openai/whisper/discussions/120#discussioncomment-3733601)

If this does not help, then please run:

```bash
pip freeze
```
And send an output.

**Comment by saravanareddy09** [comment]
PS F:\AI\ecoute> pip freeze
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
colorama==0.4.6
comtypes==1.1.14
customtkinter==5.1.3
darkdetect==0.8.0
ffmpeg-python==0.2.0
filelock==3.12.0
frozenlist==1.3.3
future==0.18.3
idna==3.4
Jinja2==3.1.2
llvmlite==0.40.1rc1
MarkupSafe==2.1.3
more-itertools==9.1.0
mpmath==1.3.0
multidict==6.0.4
networkx==3.1
numba==0.57.0
numpy==1.24.3
openai-whisper @ git+https://github.com/openai/whisper.git@248b6cb124225dd263bb9bd32d060b6517e067f8
PyAudioWPatch==0.2.12.5
pywin32==306
pywinauto==0.6.8
regex==2023.6.3
requests==2.31.0
six==1.16.0
sympy==1.12
tiktoken==0.3.3
torch==2.0.1
tqdm==4.65.0
typing_extensions==4.6.3
urllib3==2.0.3
Wave==0.0.2
yarl==1.9.2
PS F:\AI\ecoute>

**Comment by s0d3s** [comment]
@saravanareddy09

If your error has not changed, then the problem is exactly what I wrote about. You have the wrong library installed. And for some reason, `pip` did not remove it, although judging by your message, `pip` itself does not see this library.

> [Lines of code](https://github.com/graphite-project/whisper/blob/07f3db997a7ff4657f840eb5ef4b171d93aba3c9/whisper.py#L69) for which an error is thrown are not in the openai-whisper, because they belong to the same erroneous [library](https://pypi.org/project/whisper/).

Do you have multiple versions of Python installed on your system? Run this to check:
```cmd
where python
where pip
```
If there are several versions, then you used pip from the wrong version of python. In this case, you need to run the script using the "correct" version (to do this, instead of `python`, write `C:\full\path\to\python`)

You also have the following options:
 - try to manualy delete `C:\full\path\to\python_dir\lib\site-packages\whisper.py`
 - or try **full reinstall** python and `ecoute`
 - or try to use [virtual environments(like, venv)](https://www.google.com/search?q=venv+python)

> Note: Maybe you should try using an earlier version of python, like 3.9

**Comment by saravanareddy09** [comment]
after resolve few issues iam getting this issue

Traceback (most recent call last):
  File "F:\AI\ecoute\main.py", line 2, in <module>
    from AudioTranscriber import AudioTranscriber
  File "F:\AI\ecoute\AudioTranscriber.py", line 1, in <module>
    import whisper
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
![image](https://github.com/SevaSk/ecoute/assets/135105015/d862fa8d-c5c3-440e-901f-fb4bf3b9b00c)

**Comment by mulagura** [comment]
I downgraded to 3.9.5, and working like Charm

**Comment by Sahil0450** [comment]
> I downgraded to 3.9.5, and working like Charm

you downgraded python?
